﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace RestaurantViolations
{
    public partial class RestaurantViolationsPrediction
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.Text.FeaturizeText(@"InspectionType", @"InspectionType")      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"ViolationDescription", @"ViolationDescription"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"InspectionType",@"ViolationDescription"}))      
                                    .Append(mlContext.Transforms.Conversion.MapValueToKey(@"RiskCategory", @"RiskCategory"))      
                                    .Append(mlContext.Transforms.NormalizeMinMax(@"Features", @"Features"))      
                                    .Append(mlContext.MulticlassClassification.Trainers.SdcaMaximumEntropy(l1Regularization:22.3736060277166F,l2Regularization:0.03125F,labelColumnName:@"RiskCategory",featureColumnName:@"Features"))      
                                    .Append(mlContext.Transforms.Conversion.MapKeyToValue(@"PredictedLabel", @"PredictedLabel"));

            return pipeline;
        }
    }
}
